all_inputs <- sapply(RatesFitsBest, function(x) names(x$trainingData))
all_outputs <- names(all_inputs)
gloss <- unique(c(all_inputs, all_outputs))
gloss <- gloss[gloss != ".outcome"]
gloss <- cbind(
  "Code name (raw)" = gloss,
  "Code name" = gloss,
  "Description" = c(
    "Gender == Male",
    "Gender == Female",
    "Education in Years",
    "Left-handed",
    "Grandparent with PD",
    "Parent with PD",
    "Age at Baseline",
    "Time of diagnosis at baseline",
    "UPDRS I score at baseline",
    "UPDRS II score at baseline",
    "UPDRS III score at baseline",
    "Hoehn and Yahr Stage",
    "Modified Schwab and England - Overall",
    "Neuropsyc. Test (Line Orientation) - Sum 15 item",
    "Epworth Sleepiness Scale - Total",
    "Geriatric Depression Scale - Total",
    "Derived-Total Recall T-Score",
    "Derived-Delayed Recall T-Score",
    'Derived-Retention T-Score',
    'Derived-Recog. Discrim. Index T-Score',
    'Derived-(Letter Number Sequencing) Scaled Score',
    'Questionnaire for Impulsive-Compulsive Disorders in PD - Total',
    'REM Sleep Disorder Questionnaire - Total',
    "SCales for Outcomes in PD-PsychoSocial questionnaire - Total",
    'Derived-Sem. Fluency-Animal Scaled Score',
    'Montreal Cognitive Assessment - Total',
    'State-Trait Anxiety Inventory - Total',
    'Derived-Symbol Digit T-Score',
    'University of Pennsylvania Smell ID Test - Total',
    'Supine Blood Pressure - systolic',
    'Supine Blood Pressure - diastolic',
    'Supine heart rate',
    'Standing Blood Pressure - systolic',
    'Standing Blood Pressure - diastolic',
    'standing heart rate',
    'Body Mass Index',
    'Asymmetry Index for Putamen',
    'Asymmetric Index for Caudate',
    'Mean Caudate / Mean Putamen',
    'Mean Striatum (right and left)',
    'Mean Putamen (right and left)',
    'Mean Caudate (right and left)',
    'SI Result for Albumin-QT',
    'SI Result for Alkaline Phosphatase',
    'SI Result for ALT (SGPT)',
    'SI Result for APTT-QT',
    'SI Result for AST (SGOT)',
    'SI Result for Basophils',
    'SI Result for Basophils (%)',
    'SI Result for Calcium (EDTA)',
    'SI Result for Creatinine (Rate Blanked)',
    'SI Result for Eosinophils',
    'SI Result for Eosinophils (%)',
    'SI Result for Hematocrit',
    'SI Result for Hemoglobin',
    'SI Result for Lymphocytes',
    'SI Result for Lymphocytes (%)',
    'SI Result for Monocytes',
    'SI Result for Monocytes (%)',
    'SI Result for Neutrophils',
    'SI Result for Neutrophils (%)',
    'SI Result for Platelets',
    'SI Result for Prothrombin Time',
    'SI Result for RBC',
    'SI Result for Serum Bicarbonate',
    'SI Result for Serum Chloride',
    'SI Result for Serum Glucose',
    'SI Result for Serum Potassium',
    'SI Result for Serum Sodium',
    'SI Result for Serum Uric Acid',
    'SI Result for Total Bilirubin',
    'SI Result for Total Protein',
    'SI Result for Urea Nitrogen',
    'SI Result for WBC',
    'Test Value for Abeta 42',
    'Test Value for CSF Alpha-synuclein',
    'Test Value for p-Tau181P',
    'Test Value for Total tau',
    'Test Value for SCORE',
    'Test Value for Serum IGF-1',
    'Apolipoprotein E (APOE) gene (e3/e2)',
    'Apolipoprotein E (APOE) gene (e3/e3)',
    'Apolipoprotein E (APOE) gene (e4/e3)',
    'How many G in rs55785911 (DNA)',
    'How many G in rs12456492 (DNA)',
    'How many T in rs17649553 (DNA)',
    'How many G in rs11868035 (DNA)',
    'How many G in rs14235 (DNA)',
    'How many G in rs2414739 (DNA)',
    'How many T in rs11158026 (DNA)',
    'How many G in rs11060180 (DNA)',
    'How many T in rs76904798 (DNA)',
    'How many T in rs329648 (DNA)',
    'How many G in rs591323 (DNA)',
    'How many T in rs199347 (DNA)',
    'How many T in rs115462410 (DNA)',
    'How many T in rs8192591 (DNA)',
    'How many T in rs3910105 (DNA)',
    'How many T in rs356181 (DNA)',
    'How many T in rs6812193 (DNA)',
    'How many G in rs11724635 (DNA)',
    'How many G in rs34311866 (DNA)',
    'How many G in rs34884217 (DNA)',
    'How many G in rs12637471 (DNA)',
    'How many G in rs1955337 (DNA)',
    'How many T in rs6430538 (DNA)',
    'How many T in rs10797576 (DNA)',
    'How many T in rs823118 (DNA)',
    'p-Tau181P / Total tau',
    'p-Tau181P / Abeta 42',
    'Total tau / Abeta 42'
  )
)

gloss[,2] <- gsub("\\`","",gloss[,1])
gloss[,2] <- gsub("as.numeric\\(","",gloss[,2])
gloss[,2] <- gsub("\\)","",gloss[,2])


gloss <- gloss[order(gloss[,3]),]
save(gloss, file = "glossary.RData")
